; PlatformIO Project Configuration File
; ESP32-C3 dengan LovyanGFX + LVGL, ST7789 display, dan BLE (Chronos)

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

; Konfigurasi USB CDC untuk ESP32-C3
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    ; Optimasi performa
    -O2
    -DCORE_DEBUG_LEVEL=0
    ; Beri tahu LVGL di mana mencari lv_conf.h
    -I${PROJECT_DIR}/include
    -DLV_CONF_INCLUDE_SIMPLE=1

lib_deps =
    lovyan03/LovyanGFX@1.2.7
    h2zero/NimBLE-Arduino@2.3.4
    bblanchon/ArduinoJson@^6.21.3
    fbiego/ESP32Time@^2.0.6
    lvgl/lvgl@^8.3.9
    Wire
    SPI
